// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NikeRun.DataAccess.NikeRunDBContext;

#nullable disable

namespace NikeRun.DataAccess.Migrations
{
    [DbContext(typeof(NikeRunDbContext))]
    partial class NikeRunDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NikeRun.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.Images", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ImageLink")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageLink = "https://i.postimg.cc/28QHckXP/Nike-Air-Max-SYSTM-1.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageLink = "https://i.postimg.cc/qvp1WPPg/Nike-Air-Max-SYSTM-2.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageLink = "https://i.postimg.cc/Prs3QpKW/Nike-Air-Max-SYSTM-3.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageLink = "https://i.postimg.cc/3x9thLh1/Nike-Air-Max-SYSTM-4.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageLink = "https://i.postimg.cc/VsbZtB9s/Nike-Air-Max-SYSTM-5.png",
                            ProductId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageLink = "https://i.postimg.cc/MGCVJRnt/Nike-Air-Zoom-Pegasus-39-1.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageLink = "https://i.postimg.cc/76S7H674/Nike-Air-Zoom-Pegasus-39-2.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageLink = "https://i.postimg.cc/2ymWVDFZ/Nike-Air-Zoom-Pegasus-39-3.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageLink = "https://i.postimg.cc/sf9SbMs9/Nike-Air-Zoom-Pegasus-39-4.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImageLink = "https://i.postimg.cc/KjNMTHJs/Nike-Air-Zoom-Pegasus-39-5.png",
                            ProductId = 2
                        },
                        new
                        {
                            Id = 11,
                            ImageLink = "https://i.postimg.cc/85bwHJC7/Nike-Winflo-8-1.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 12,
                            ImageLink = "https://i.postimg.cc/yxYjr1Jv/Nike-Winflo-8-2.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 13,
                            ImageLink = "https://i.postimg.cc/kG1c00K9/Nike-Winflo-8-3.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 14,
                            ImageLink = "https://i.postimg.cc/Pr7y2kdQ/Nike-Winflo-8-4.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 15,
                            ImageLink = "https://i.postimg.cc/Y2bbLWVV/Nike-Winflo-8-5.png",
                            ProductId = 3
                        },
                        new
                        {
                            Id = 16,
                            ImageLink = "https://i.postimg.cc/Nf40QRDC/Nike-Zoom-X-Streakfly-1.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 17,
                            ImageLink = "https://i.postimg.cc/Kctzs6M2/Nike-Zoom-X-Streakfly-2.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 18,
                            ImageLink = "https://i.postimg.cc/TYGw8tVW/Nike-Zoom-X-Streakfly-3.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 19,
                            ImageLink = "https://i.postimg.cc/XY17C3Tw/Nike-Zoom-X-Streakfly-4.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 20,
                            ImageLink = "https://i.postimg.cc/3xxxNWb8/Nike-Zoom-X-Streakfly-5.png",
                            ProductId = 4
                        },
                        new
                        {
                            Id = 21,
                            ImageLink = "https://i.postimg.cc/bJBQCKDb/zoomx-streakfly-1.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 22,
                            ImageLink = "https://i.postimg.cc/7663Nx6w/zoomx-streakfly-2.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 23,
                            ImageLink = "https://i.postimg.cc/6q4CDYnP/zoomx-streakfly-3.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 24,
                            ImageLink = "https://i.postimg.cc/Th8nGgc3/zoomx-streakfly-4.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 25,
                            ImageLink = "https://i.postimg.cc/XNrhjWgR/zoomx-streakfly-5.png",
                            ProductId = 5
                        },
                        new
                        {
                            Id = 26,
                            ImageLink = "https://i.postimg.cc/YSw1LYxV/Nike-Zoom-X-Invincible-Run-Flyknit-2-1.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 27,
                            ImageLink = "https://i.postimg.cc/QxwgsRKj/Nike-Zoom-X-Invincible-Run-Flyknit-2-2.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 28,
                            ImageLink = "https://i.postimg.cc/9Q9dfJyZ/Nike-Zoom-X-Invincible-Run-Flyknit-2-3.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 29,
                            ImageLink = "https://i.postimg.cc/vTD9wzQ1/Nike-Zoom-X-Invincible-Run-Flyknit-2-4.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 30,
                            ImageLink = "https://i.postimg.cc/XJsFPh0S/Nike-Zoom-X-Invincible-Run-Flyknit-2-5.png",
                            ProductId = 6
                        },
                        new
                        {
                            Id = 31,
                            ImageLink = "https://i.postimg.cc/cL6s7bFt/Nike-Zoom-X-Streakfly-1.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 32,
                            ImageLink = "https://i.postimg.cc/nh5n3GWR/Nike-Zoom-X-Streakfly-2.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 33,
                            ImageLink = "https://i.postimg.cc/d1cwYtwG/Nike-Zoom-X-Streakfly-3.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 34,
                            ImageLink = "https://i.postimg.cc/wM0pLXJk/Nike-Zoom-X-Streakfly-4.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 35,
                            ImageLink = "https://i.postimg.cc/j2sTDgW5/Nike-Zoom-X-Streakfly-5.png",
                            ProductId = 7
                        },
                        new
                        {
                            Id = 36,
                            ImageLink = "https://i.postimg.cc/vB7MHFZk/Nike-Zoom-X-Streakfly-6.png",
                            ProductId = 7
                        });
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.ProductDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Size")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDetails");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Cassette mixtapes. Music videos on TV. Shopping centre arcades. The '80s were fun and wild! We're celebrating that wicked cool era with the Nike Air Max SYSTM. From the big and bold Air unit to design lines (inspired by our favourite throwback Air Max shoes), it's all about bringing back what's cool to a new generation.",
                            Price = 3500m,
                            ProductId = 1,
                            Size = 8m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Cassette mixtapes. Music videos on TV. Shopping centre arcades. The '80s were fun and wild! We're celebrating that wicked cool era with the Nike Air Max SYSTM. From the big and bold Air unit to design lines (inspired by our favourite throwback Air Max shoes), it's all about bringing back what's cool to a new generation.",
                            Price = 3500m,
                            ProductId = 1,
                            Size = 9m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Cassette mixtapes. Music videos on TV. Shopping centre arcades. The '80s were fun and wild! We're celebrating that wicked cool era with the Nike Air Max SYSTM. From the big and bold Air unit to design lines (inspired by our favourite throwback Air Max shoes), it's all about bringing back what's cool to a new generation.",
                            Price = 3500m,
                            ProductId = 1,
                            Size = 10m
                        },
                        new
                        {
                            Id = 4,
                            Description = "The Nike Air Zoom Pegasus 39 is made for runners of ALL levels—from athletics speedsters to freeze tig champs. Chase your goals with an extra bounce to your stride thanks to our innovative Zoom Air. It's also breathable up top and snug around the laces so you can feel cool, comfortable and confident with every mile",
                            Price = 5000m,
                            ProductId = 2,
                            Size = 8m
                        },
                        new
                        {
                            Id = 5,
                            Description = "The Nike Air Zoom Pegasus 39 is made for runners of ALL levels—from athletics speedsters to freeze tig champs. Chase your goals with an extra bounce to your stride thanks to our innovative Zoom Air. It's also breathable up top and snug around the laces so you can feel cool, comfortable and confident with every mile",
                            Price = 5000m,
                            ProductId = 2,
                            Size = 9m
                        },
                        new
                        {
                            Id = 6,
                            Description = "The Nike Air Zoom Pegasus 39 is made for runners of ALL levels—from athletics speedsters to freeze tig champs. Chase your goals with an extra bounce to your stride thanks to our innovative Zoom Air. It's also breathable up top and snug around the laces so you can feel cool, comfortable and confident with every mile",
                            Price = 5000m,
                            ProductId = 2,
                            Size = 10m
                        },
                        new
                        {
                            Id = 7,
                            Description = "If running is a daily habit, you need support to match your speed. The Nike Winflo 8 brings back the cushioning you love and pairs it with details like a translucent upper and Flywire technology for a snug, stable fit for long road runs.",
                            Price = 8500m,
                            ProductId = 3,
                            Size = 8m
                        },
                        new
                        {
                            Id = 8,
                            Description = "If running is a daily habit, you need support to match your speed. The Nike Winflo 8 brings back the cushioning you love and pairs it with details like a translucent upper and Flywire technology for a snug, stable fit for long road runs.",
                            Price = 8500m,
                            ProductId = 3,
                            Size = 9m
                        },
                        new
                        {
                            Id = 9,
                            Description = "If running is a daily habit, you need support to match your speed. The Nike Winflo 8 brings back the cushioning you love and pairs it with details like a translucent upper and Flywire technology for a snug, stable fit for long road runs.",
                            Price = 8500m,
                            ProductId = 3,
                            Size = 10m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Continue the next evolution of speed with a racing shoe made to help you chase new goals and records. It helps improve comfort and breathability with a redesigned upper. From a 10K to a marathon, this model, like the previous version, has the responsive cushioning and secure support to push you towards your personal best.",
                            Price = 9000m,
                            ProductId = 4,
                            Size = 8m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Continue the next evolution of speed with a racing shoe made to help you chase new goals and records. It helps improve comfort and breathability with a redesigned upper. From a 10K to a marathon, this model, like the previous version, has the responsive cushioning and secure support to push you towards your personal best.",
                            Price = 9000m,
                            ProductId = 4,
                            Size = 9m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Continue the next evolution of speed with a racing shoe made to help you chase new goals and records. It helps improve comfort and breathability with a redesigned upper. From a 10K to a marathon, this model, like the previous version, has the responsive cushioning and secure support to push you towards your personal best.",
                            Price = 9000m,
                            ProductId = 4,
                            Size = 10m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Our lightest racing shoe, the Nike ZoomX Streakfly is all about the speed you need to take on the competition in a mile, 5K or 10K race. Low profile with sleek details, it feels like it disappears on your foot to help you better connect with the road on the way to your personal best. Pops of bright colour add a fun refresh, so you can turn heads at the finishing line.",
                            Price = 9500m,
                            ProductId = 5,
                            Size = 8m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Our lightest racing shoe, the Nike ZoomX Streakfly is all about the speed you need to take on the competition in a mile, 5K or 10K race. Low profile with sleek details, it feels like it disappears on your foot to help you better connect with the road on the way to your personal best. Pops of bright colour add a fun refresh, so you can turn heads at the finishing line.",
                            Price = 9500m,
                            ProductId = 5,
                            Size = 9m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Our lightest racing shoe, the Nike ZoomX Streakfly is all about the speed you need to take on the competition in a mile, 5K or 10K race. Low profile with sleek details, it feels like it disappears on your foot to help you better connect with the road on the way to your personal best. Pops of bright colour add a fun refresh, so you can turn heads at the finishing line.",
                            Price = 9500m,
                            ProductId = 5,
                            Size = 10m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Keep pushing your runs to the limit. The Nike ZoomX Invincible Run Flyknit 2 keeps you going with the same super-soft feel that lets you feel the potential when your foot hits the pavement. We created the shoe with plenty of springy responsiveness and our highest level of support to keep you feeling secure and competitive. It's one of our most tested shoes, still designed for you to stay on the road and away from the sidelines.",
                            Price = 7500m,
                            ProductId = 6,
                            Size = 8m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Keep pushing your runs to the limit. The Nike ZoomX Invincible Run Flyknit 2 keeps you going with the same super-soft feel that lets you feel the potential when your foot hits the pavement. We created the shoe with plenty of springy responsiveness and our highest level of support to keep you feeling secure and competitive. It's one of our most tested shoes, still designed for you to stay on the road and away from the sidelines.",
                            Price = 7500m,
                            ProductId = 6,
                            Size = 9m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Keep pushing your runs to the limit. The Nike ZoomX Invincible Run Flyknit 2 keeps you going with the same super-soft feel that lets you feel the potential when your foot hits the pavement. We created the shoe with plenty of springy responsiveness and our highest level of support to keep you feeling secure and competitive. It's one of our most tested shoes, still designed for you to stay on the road and away from the sidelines.",
                            Price = 7500m,
                            ProductId = 6,
                            Size = 10m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Our lightest racing shoe, the Nike ZoomX Streakfly is all about the speed you need to take on the competition in a mile, 5K or 10K race. Low profile with sleek details, it feels like it disappears on your foot to help you better connect with the road on the way to your personal best.",
                            Price = 7000m,
                            ProductId = 7,
                            Size = 8m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Our lightest racing shoe, the Nike ZoomX Streakfly is all about the speed you need to take on the competition in a mile, 5K or 10K race. Low profile with sleek details, it feels like it disappears on your foot to help you better connect with the road on the way to your personal best.",
                            Price = 7000m,
                            ProductId = 7,
                            Size = 9m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Our lightest racing shoe, the Nike ZoomX Streakfly is all about the speed you need to take on the competition in a mile, 5K or 10K race. Low profile with sleek details, it feels like it disappears on your foot to help you better connect with the road on the way to your personal best.",
                            Price = 7000m,
                            ProductId = 7,
                            Size = 10m
                        });
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.Products", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Kids",
                            ProductName = "Nike Air Max SYSTM"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Kids",
                            ProductName = "Nike Air Zoom Pegasus 39"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Mens",
                            ProductName = "Nike Winflo 8"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Mens",
                            ProductName = "Nike ZoomX Vaporfly Next 2"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Mens",
                            ProductName = "Nike ZoomX Streakfly"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Womens",
                            ProductName = "Nike ZoomX Invincible Run Flyknit 2"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Womens",
                            ProductName = "Nike ZoomX Streakfly"
                        });
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefToken")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.Cart", b =>
                {
                    b.HasOne("NikeRun.Domain.Entities.Products", "Products")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NikeRun.Domain.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.Images", b =>
                {
                    b.HasOne("NikeRun.Domain.Entities.Products", "Product")
                        .WithMany("Image")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.ProductDetails", b =>
                {
                    b.HasOne("NikeRun.Domain.Entities.Products", "Product")
                        .WithMany("ProductDetails")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NikeRun.Domain.Entities.Users", "Users")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NikeRun.Domain.Entities.Products", b =>
                {
                    b.Navigation("Image");

                    b.Navigation("ProductDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
